version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "AIRCLOUD-PL"
    
  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
    reviewers:
      - "AIRCLOUD-PL"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "AIRCLOUD-PL"
